language: python

python:
  - '3.3'

env:
  global:
    - secure: CjZqqnPUed0WGqAetzL4ehL7JTRpP2PWkjxDRFERwsCN6BbfpjByZlXK+/i/654NbwC8e/xJlq/IA/+pmHB/PkehnW28kMdLwok+nQa2yiASNMZVEaDuvfCdjlkUyQ63rUc4LcjmYt2wmcRc6F3P5V+55q3bYE9r3IgOfvkV1eo=

script:
  - npm install -g grunt-cli
  - python py/minify.py

after_script:
  - cd $HOME
  - git config --global user.email "${GIT_EMAIL}"
  - git config --global user.name "${GIT_NAME}"
  - git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/sniksnp/image-slider-game gh-pages > /dev/null
  - cd gh-pages
  - git rm -rf * .travis.yml .gitignore
  - cp -Rf $HOME/build/sniksnp/image-slider-game/minified.html $HOME/build/sniksnp/image-slider-game/im .
  - git add -f .
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER"
  - git push -fq origin gh-pages > /dev/null
